# Generated by Django 3.1.2 on 2020-10-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organistaion_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organisation_name', models.CharField(max_length=200)),
                ('Organisation_email', models.EmailField(max_length=254)),
                ('Organisation_phone_number', models.BigIntegerField()),
                ('Organisation_message', models.TextField()),
            ],
        ),
    ]
