# Generated by Django 3.1.2 on 2020-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_paws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happystories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('happy_story', models.TextField()),
                ('admin_verification', models.BooleanField(default=False)),
            ],
        ),
    ]
