# Generated by Django 3.1.2 on 2020-12-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeredcities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registeredshelters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=200)),
                ('shelter_location', models.CharField(max_length=200)),
                ('shelter_email', models.EmailField(max_length=254)),
                ('shelter_contact_number', models.BigIntegerField()),
                ('shelter_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='little_paws_adopt_foster.registeredcities')),
            ],
        ),
        migrations.CreateModel(
            name='Petdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_image', models.ImageField(upload_to='pics')),
                ('pet_type', models.CharField(choices=[('DOG', 'dog'), ('CAT', 'cat')], max_length=10)),
                ('pet_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=10)),
                ('pet_breed', models.CharField(max_length=50)),
                ('pet_age', models.CharField(max_length=50)),
                ('available_for_adoption', models.BooleanField(default=True)),
                ('availabe_for_foster', models.BooleanField(default=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('pet_shelter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='little_paws_adopt_foster.registeredshelters')),
            ],
        ),
    ]
